name: Deploy Infrastructure

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
        working-directory: ./infra
      - run: terraform apply -auto-approve
        working-directory: ./infra